### ISSUE TITLE
Continuous Deployment card is not clear

### ISSUE THREAD

**Issue by ilya-v-trofimov** [kids-code-games/variables-war#4]
As per description, CD card allows to 
> Play twice when the selected var is a multiple of 7

But the question is: 
Does player keep this card forever on the variable he chooses and plays twice every time the var is mult.of 7? 
Or is it played *only once*, when either of vars is mult. of 7?

I would opt for the former: card stays forever (or until it's removed by opponent's attack)

**Comment by ealliaume** [comment]
Yes, you keep this card forever on the variable you selected

**Comment by ealliaume** [comment]
Description updated
