### ISSUE TITLE
Typo on Mob Programming card

### ISSUE THREAD

**Issue by buchmiller** [kids-code-games/variables-war#7]
The Mob Programming card says "He guys, let's work 
as a team!"
I'm guessing that "He" should be "Hey".

**Comment by michaelmior** [comment]
The Pair programming card has the same typo with "He mate!"

**Comment by michaelmior** [comment]
If this is being fixed, I would also suggest changing "guys" with something gender neutral such as "everyone."

**Comment by sholladay** [comment]
Another option instead of "guys" is "folks".

**Comment by ealliaume** [comment]
Thanks!

**Comment by buchmiller** [comment]
Don't forget to update the images in the readme.
